#! /bin/sh

killall panel
panel &

bspc monitor -d '' '' '' '' ''

bspc config border_width        2
bspc config window_gap          8
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a MPlayer floating=on
bspc rule -a feh floating=on
bspc rule -a gifview floating=on

bspc config focus_follows_pointer true

bspc config focused_border_color "#C1B99E"
bspc config normal_border_color "#605D54"
bspc config urgent_border_color "#605D54"
